import { chromium } from "@playwright/test";
const browser = await chromium.launch({ executablePath: "/opt/pw-browsers/chromium" });
const page = await browser.newPage({ viewport: { width: 390, height: 844 } });
const msgs: string[] = [];
page.on("console", (m) => { if (m.type() === "error" || m.type() === "warning") msgs.push(m.text()); });
page.on("pageerror", (e) => msgs.push("PAGEERROR " + String(e)));
await page.goto(process.argv[2], { waitUntil: "load" });
await page.waitForTimeout(4000);
await browser.close();
console.log(msgs.join("\n---\n").slice(0, 3000) || "no console errors");
